### ISSUE TITLE
'Fetch Logs' button on API example page causes JSON error

### ISSUE THREAD

**Issue by johnmaccormick** [DickinsonCollege/FarmData2#453] opened 2022-05-04 17:15 UTC
The 'Fetch Logs' button on the page [http://localhost/farm/fd2-example/api](http://localhost/farm/fd2-example/api) causes the following error:

* SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data

**Comment by braughtg** [comment] 2022-05-04 18:16
Duplicate of #422.

**Closed by braughtg** 2022-05-04 18:16 UTC
Labels: bug
